# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91d8f7d7521de3338d253db7c593e5d56ced7f66df2ada11eccb83dd52d9afb4d22b585db03f2b1fb0f03471ce0659abd26f28f9f0bfa8650af0ece19e96b6ef

test:
  secret_key_base: 0a734bcf0ee70ba951ff4b0fc5dba3009f81f6a58681dba0d5d1f485f84d83b965a0abd7fa7e8332eff8858d457bf486bc37dd9d940096470e88c72f624984d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
